---
- name: create wheel group when not exists
  group:
    name: "wheel"
    state: present
  when:
    - role_usermanager_wheel_allow_nopasswd is defined
    - role_usermanager_wheel_allow_nopasswd

- name: install sudoers
  template:
    src: etc/sudoers.d/wheel-nopasswd.conf
    dest: /etc/sudoers.d/wheel-nopasswd
    owner: root
    group: root
    mode: 0440
  when:
    - role_usermanager_wheel_allow_nopasswd is defined
    - role_usermanager_wheel_allow_nopasswd

- name: remove wheel nopasswd, if disabled
  file:
    path: /etc/sudoers.d/wheel-nopasswd
    state: absent
  when: 
    - role_usermanager_wheel_allow_nopasswd is defined
    - not role_usermanager_wheel_allow_nopasswd

- name: create user group (unix)
  group:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ system_users}}"
  when:
    - system_users is defined
    - item.create_group is defined and item.create_group
    - item.state == 'present'

- name: create/delete users
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    home: "{{ item.home }}"
    shell: "{{ item.shell }}"
    force: "{{ item.force }}"
    group: "{{ item.name if item.create_group is defined and item.create_group }}"
    groups: "{{ item.groups }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ system_users }}"
  when:
    - system_users|length > 0

- name: create authorized_keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.authorized_keys }}"
    validate_certs: no
    state: "present"
  with_items:
    - "{{ system_users }}"
  when:
    - item.state == 'present'
    - item.authorized_keys is defined
    - not ansible_check_mode

- name: delete unix groups
  group:
    name: "{{ item.name }}"
    state: absent
  with_items:
    - "{{ system_users}}"
  when:
    - item.create_group is defined and item.create_group
    - item.state == 'absent'


